# Generated by Django 4.2.2 on 2023-06-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0003_alter_estudiante_edad_alter_estudiante_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre de paises')),
                ('capital', models.CharField(max_length=30, verbose_name='Nombre de capitales')),
            ],
        ),
    ]
